[Preferences]
WebUI\Port=8080
WebUI\AuthSubnetWhitelistEnabled=true
WebUI\AuthSubnetWhitelist=172.16.0.0/12, 192.168.0.0/16
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=true
WebUI\HostHeaderValidation=false
